name: binary
description: A PhoenixSocket example
version: 0.0.2
homepage: https://www.github.com/matehat/phoenix-socket-dart
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  logging: ^1.0.0
  phoenix_socket:
    path: ../../

  uuid: ^3.0.1

dev_dependencies: {}
